apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
data:
  API_TARGET: {{ .Values.app.apiTarget | quote }}
  VITE_ALLOWED_HOSTS: {{ include "portfolio-tracker.allowedHosts" . | quote }}
