{{- if .Values.postgres.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}-postgres
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "portfolio-tracker.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: postgres
  template:
    metadata:
      labels:
        {{- include "portfolio-tracker.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.auth.database | quote }}
            - name: POSTGRES_USER
              value: {{ .Values.postgres.auth.username | quote }}
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "portfolio-tracker.fullname" . }}-postgres
                  key: postgres-password
          {{- if .Values.postgres.persistence.enabled }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: pgdata
          {{- end }}
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.auth.username | quote }}]
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", {{ .Values.postgres.auth.username | quote }}]
            initialDelaySeconds: 5
            periodSeconds: 5
      {{- if .Values.postgres.persistence.enabled }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "portfolio-tracker.fullname" . }}-postgres
      {{- end }}
{{- end }}
