apiVersion: v1
kind: Secret
metadata:
  name: {{ include "portfolio-tracker.fullname" . }}
  labels:
    {{- include "portfolio-tracker.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "portfolio-tracker.databaseUrl" . | quote }}
